{% set pyproject = load_file_data('../pyproject.toml', from_recipe_dir=True) %}
{% set name = pyproject.get('project').get('name') %}
{% set description = pyproject.get('project').get('description') %}
{% set version = environ.get('SETUPTOOLS_SCM_PRETEND_VERSION', "0.0.0.dev") %}
{% set license = pyproject.get('project').get('license') %}
{% set build_deps = pyproject.get("build-system", {}).get("requires", []) %}
{% set deps = pyproject.get('project', {}).get('dependencies', []) %}
{% set conda_deps = pyproject.get('tool', {}).get('conda', {}).get('environment', {}).get('dependencies',[]) %}
{% set test_deps = pyproject.get('project', {}).get('optional-dependencies', {}).get('test',[]) %}
{% set conda_test_deps = pyproject.get('tool', {}).get('conda', {}).get('environment', {}).get('test-dependencies',[]) %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ..

build:
  script_env:
    # forge cmake generator and compilers for scikit-build without msvc on Windows
    - CMAKE_GENERATOR=MinGW Makefiles # [win]
    - CXX=g++ # [win]
    - CC=gcc # [win]
    # Force static build on Windows to allow skipping run export of m2w64 stdlib
    - LDFLAGS=-static -static-libgcc -static-libstdc++   # [win]
  ignore_run_exports_from:
    # Avoid automatic run export of m2w64 stdlib on windows (that forces hard regression of msvc libs)
    - {{ compiler('c') }} # [win]
    - {{ compiler('cxx') }} # [win]
  script:
    - {{PYTHON}} -m pip install --no-deps  --no-build-isolation . -vv

requirements:
  host:
    - python
    {% for dep in build_deps %}
    - {{ dep }}
    {% endfor  %}
    - cmake
    - make                                 # [not win]
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  run:
    - python
    {% for dep in deps + conda_deps %}
    - {{ dep }}
    {% endfor %}

test:
  requires:
    {% for dep in test_deps + conda_test_deps %}
    - {{ dep }}
    {% endfor %}
  source_files:
    - test/*.py
  commands:
    - canestrad -h
    - periodise -h
    - s2v -h
    - mcsail -h
    - pytest -v

about:
  description: {{ description }}
  summary: {{ description }}
  license: CeCILL_C
